/**
 * Shared Slack event utilities
 */

import type { MessageHandlerConfig } from "./config";

// ============================================================================
// Event Filtering
// ============================================================================

/**
 * Type for generic Slack event with common properties
 */
interface SlackEventBase {
  bot_id?: string;
  user?: string;
}

/**
 * Check if a Slack event was generated by the bot itself
 * Used to filter out self-generated events to prevent loops
 *
 * @param event - Slack event to check
 * @param config - Message handler configuration
 * @param allowMentions - If true, allow self-generated messages that mention the bot (for testing)
 */
export function isSelfGeneratedEvent(
  event: SlackEventBase,
  config: MessageHandlerConfig,
  allowMentions: boolean = false
): boolean {
  const botUserId = config.slack.botUserId;
  const botId = config.slack.botId;

  const isSelf =
    (botId && event.bot_id && event.bot_id === botId) ||
    (botUserId && event.user === botUserId);

  // If allowMentions is true and this is a mention, allow it (for testing via messaging API)
  if (isSelf && allowMentions) {
    return false; // Don't filter - allow it
  }

  return !!isSelf;
}
