/**
 * Shared Slack event utilities
 */

import { createLogger } from "@peerbot/core";
import type { WebClient } from "@slack/web-api";
import type { MessageHandlerConfig } from "./config";

const logger = createLogger("slack-utils");

// ============================================================================
// Event Filtering
// ============================================================================

/**
 * Type for generic Slack event with common properties
 */
interface SlackEventBase {
  bot_id?: string;
  user?: string;
}

/**
 * Check if a Slack event was generated by the bot itself
 * Used to filter out self-generated events to prevent loops
 */
export function isSelfGeneratedEvent(
  event: SlackEventBase,
  config: MessageHandlerConfig
): boolean {
  const botUserId = config.slack.botUserId;
  const botId = config.slack.botId;

  const isSelf =
    (botId && event.bot_id && event.bot_id === botId) ||
    (botUserId && event.user === botUserId);

  return !!isSelf;
}

// ============================================================================
// Thread Status Management
// ============================================================================

/**
 * Payload for assistant.threads.setStatus API
 */
interface ThreadStatusPayload {
  channel_id: string;
  thread_ts: string;
  status: string;
  loading_messages?: string[];
}

/**
 * Set thread status using assistant.threads.setStatus API
 * Shared utility to avoid duplication
 */
export async function setThreadStatus(
  client: WebClient,
  channelId: string,
  threadTs: string,
  status?: string,
  loadingMessages?: string[]
): Promise<void> {
  if (!threadTs) {
    return;
  }

  try {
    const payload: ThreadStatusPayload = {
      channel_id: channelId,
      thread_ts: threadTs,
      status: status ?? "",
    };

    if (loadingMessages && loadingMessages.length > 0) {
      payload.loading_messages = loadingMessages;
    }

    await client.apiCall("assistant.threads.setStatus", { ...payload });
  } catch (error) {
    logger.warn(
      `Failed to set status '${status || "<clear>"}' for thread ${threadTs}:`,
      error
    );
  }
}
