/**
 * Shared Slack event utilities
 */

import type { MessageHandlerConfig } from "./config";

// ============================================================================
// Event Filtering
// ============================================================================

/**
 * Type for generic Slack event with common properties
 */
interface SlackEventBase {
  bot_id?: string;
  user?: string;
}

/**
 * Check if a Slack event was generated by the bot itself
 * Used to filter out self-generated events to prevent loops
 */
export function isSelfGeneratedEvent(
  event: SlackEventBase,
  config: MessageHandlerConfig
): boolean {
  const botUserId = config.slack.botUserId;
  const botId = config.slack.botId;

  const isSelf =
    (botId && event.bot_id && event.bot_id === botId) ||
    (botUserId && event.user === botUserId);

  return !!isSelf;
}
