#!/usr/bin/env bash
# Generate pre-compiled Tailwind CSS for the settings page
# Run this when settings-page.ts Tailwind classes change
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
GATEWAY_DIR="$ROOT_DIR/packages/gateway"

echo "Generating settings page CSS..."

# Generate CSS using Tailwind v3 CLI
CSS=$(bunx tailwindcss@3 \
  -c "$GATEWAY_DIR/tailwind.config.js" \
  -i "$GATEWAY_DIR/src/routes/public/settings-input.css" \
  --minify)

if [ -z "$CSS" ]; then
  echo "Error: Tailwind CSS generation produced empty output" >&2
  exit 1
fi

# Write as TypeScript constant
cat > "$GATEWAY_DIR/src/routes/public/settings-page-styles.ts" << 'HEADER'
/**
 * Pre-compiled Tailwind CSS for the settings page.
 * Generated by: scripts/generate-settings-css.sh
 * DO NOT EDIT MANUALLY - regenerate with: bun run generate:settings-css
 */
HEADER

echo "export const settingsPageCSS = \`" >> "$GATEWAY_DIR/src/routes/public/settings-page-styles.ts"
echo "$CSS" >> "$GATEWAY_DIR/src/routes/public/settings-page-styles.ts"
echo "\`;" >> "$GATEWAY_DIR/src/routes/public/settings-page-styles.ts"

echo "Done! CSS written to packages/gateway/src/routes/public/settings-page-styles.ts"
